image:
  repository: ghcr.io/eodcgmbh/coverage-maps/coverage_maps
  tag: 2025.11.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "apisix"
  hosts:
    - host: "coverage.dev.services.eodc.eu"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "coverage.dev.services.eodc.eu"
      secretName: coverage-letsencrypt-tls