image:
  repository: ghcr.io/eodcgmbh/coverage-maps/coverage_maps
  tag: 2025.11.1
  pullPolicy: IfNotPresent

service:
  port: 4000

stac:
  service:
    externalName: 10.10.80.127
    port: 5000

ingress:
  enabled: true
  className: "apisix"
  hosts:
    - host: "coverage.dev.services.eodc.eu"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []