apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coverage-map.fullname" . }}
  labels:
    app: {{ include "coverage-map.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "coverage-map.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "coverage-map.name" . }}
    spec:
      containers:
        - name: coverage-map
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: coverage-map-db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: coverage-map-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coverage-map-db-secret
                  key: DB_PASSWORD

