---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coverage-map.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coverage-map.fullname" . }}-stac-connection
spec:
  type: ExternalName
  externalName: {{ .Values.stac.service.externalName }}
  ports:
    - port: {{ .Valuess.stac.service.port }}
      targetPort: {{ .Values.stac.service.port }}
      protocol: TCP
---