## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: "registry.eodc.eu"
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##

## @param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespaceapi
##
namespaceOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []

## @section EODAG Server parameters

## CS Group EODAG Server image version
## ref: https://hub.docker.com/r/csspace/eodag-server
## @param image.registry EODAG Server image registry
## @param image.repository EODAG Server image repository
## @param image.tag Overrides the EODAG Server image tag whose default is the chart appVersion (immutable tags are recommended)
## @param image.digest EODAG Server image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy EODAG Server image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
## Number of replicas to deploy
##
image:
  registry: "registry.eodc.eu"
  repository: "eodc/eodag-server"
  tag: "eodag-server-latest"
  digest: ""
  pullPolicy: Always
  pullSecrets: []

## @param replicaCount Number of EODAG Server replicas
##
replicaCount: 1

## Configure extra options for EODAG Server containers' liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## @param startupProbe.enabled Enable startupProbe on EODAG Server containers
## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
## @param startupProbe.periodSeconds Period seconds for startupProbe
## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
## @param startupProbe.failureThreshold Failure threshold for startupProbe
## @param startupProbe.successThreshold Success threshold for startupProbe
##
startupProbe:
  enabled: false
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
## @param livenessProbe.enabled Enable livenessProbe on EODAG Server containers
## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param livenessProbe.periodSeconds Period seconds for livenessProbe
## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param livenessProbe.successThreshold Success threshold for livenessProbe
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
## @param readinessProbe.enabled Enable readinessProbe on EODAG Server containers
## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param readinessProbe.periodSeconds Period seconds for readinessProbe
## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: false
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

## @param customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe: {}

## @param customReadinessProbe Custom readinessProbe that overrides the default one
##
customReadinessProbe: {}

## EODAG Server resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits The resources limits for the EODAG Server containers
## @param resources.requests The requested resources for the EODAG Server containers
##
resources:
  limits: {}
  requests: {}

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled EODAG Server pods' Security Context
## @param podSecurityContext.fsGroup Set EODAG Server pod's Security Context fsGroup
##
podSecurityContext:
  enabled: false
  fsGroup: 1001

## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param containerSecurityContext.enabled Enabled EODAG Server containers' Security Context
## @param containerSecurityContext.runAsUser Set EODAG Server containers' Security Context runAsUser
## @param containerSecurityContext.allowPrivilegeEscalation Set EODAG Server containers' Security Context allowPrivilegeEscalation
## @param containerSecurityContext.capabilities.drop Set EODAG Server containers' Security Context capabilities to be dropped
## @param containerSecurityContext.readOnlyRootFilesystem Set EODAG Server containers' Security Context readOnlyRootFilesystem
## @param containerSecurityContext.runAsNonRoot Set EODAG Server container's Security Context runAsNonRoot
##
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - all
  readOnlyRootFilesystem: false
  runAsNonRoot: true

## @param command Override default container command (useful when using custom images)
##
command: []

## @param args Override default container args (useful when using custom images). Overrides the defaultArgs.
##
args: []

## EODAG Server application ports
## @param containerPorts.http EODAG Server application HTTP port number
containerPorts:
  http: 5000

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  medium: ""
  sizeLimit: 8Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  dataSource: {}
  existingClaim: ""
  hostPath: ""
  annotations: {}
  labels: {}
  selector: {}

## @param hostAliases EODAG Server pods host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## @param podLabels Extra labels for EODAG Server pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## @param podAnnotations Annotations for EODAG Server pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## @param podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""

## @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft

## Node affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  type: ""
  key: ""
  values: []

## @param affinity Affinity for EODAG Server pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## @param nodeSelector Node labels for EODAG Server pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## @param tolerations Tolerations for EODAG Server pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param schedulerName Name of the k8s scheduler (other than default)
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""

## @param shareProcessNamespace Enable shared process namespace in a pod.
## If set to false (default), each container will run in separate namespace,  will have PID=1.
## If set to true, the /pause will run as init process and will reap any zombie PIDs,
## for example, generated by a custom exec probe running longer than a probe timeoutSeconds.
## Enable this only if customLivenessProbe or customReadinessProbe is used and zombie PIDs are accumulating.
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
##
shareProcessNamespace: false

## @param topologySpreadConstraints Topology Spread Constraints for pod assignment
## https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
##
topologySpreadConstraints: []

## @param updateStrategy.type EODAG Server statefulset strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/s/statefulset/#update-strategies
##
updateStrategy:
  type: RollingUpdate

## @param priorityClassName EODAG Server pods' priorityClassName
##
priorityClassName: ""

## @param runtimeClassName Name of the runtime class to be used by pod(s)
## ref: https://kubernetes.io/docs/concepts/containers/runtime-class/
##
runtimeClassName: ""

## @param lifecycleHooks for the EODAG Server container(s) to automate configuration before or after startup
##
lifecycleHooks: {}

## @param extraEnvVars Array with extra environment variables to add to EODAG Server nodes
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []

## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for EODAG Server nodes
##
extraEnvVarsCM: ""

## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for EODAG Server nodes
##
extraEnvVarsSecret: ""

## @param extraVolumes Optionally specify extra list of additional volumes for the EODAG Server pod(s)
##
extraVolumes: []

## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for the EODAG Server container(s)
##
extraVolumeMounts: []

## @param sidecars Add additional sidecar containers to the EODAG Server pod(s)
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: []

## @param initContainers Add additional init containers to the EODAG Server pod(s)
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'echo "hello world"']
##
initContainers: []

## @param logLevel Supported values are 0 (no log), 1 (no logging but progress bar), 2 (INFO) or 3 (DEBUG).
logLevel: 2

## @param productTypes Optional overwrite of product types default configuration
## ref: https://github.com/CS-SI/eodag/blob/masster/eodag/resources/product_types.yml
productTypes: ""
